const users = {
  1: { "id": 1, "email": "ashackel0@auda.org.au" },
  2: { "id": 2, "email": "neayrs1@dell.com" },
  3: { "id": 3, "email": "rmaultby2@twitpic.com" },
  4: { "id": 4, "email": "jsproat3@diigo.com" },
  5: { "id": 5, "email": "gpashby4@senate.gov" }
}

const polls = {
  1: { "id": 1, "creator_id": 1, "title": "I Accuse", "description": "pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit", "created_at": "12/14/2020", "closes_at": "4/21/2021", "admin_link": "http://engadget.com/parturient/montes/nascetur/ridiculus/mus/etiam.aspx?venenatis=sit&lacinia=amet&aenean=cursus&sit=id&amet=turpis&justo=integer&morbi=aliquet&ut=massa&odio=id&cras=lobortis&mi=convallis&pede=tortor&malesuada=risus&in=dapibus&imperdiet=augue&et=vel&commodo=accumsan&vulputate=tellus&justo=nisi&in=eu&blandit=orci&ultrices=mauris&enim=lacinia&lorem=sapien&ipsum=quis&dolor=libero&sit=nullam&amet=sit&consectetuer=amet&adipiscing=turpis&elit=elementum&proin=ligula&interdum=vehicula&mauris=consequat&non=morbi&ligula=a&pellentesque=ipsum&ultrices=integer&phasellus=a&id=nibh&sapien=in&in=quis&sapien=justo&iaculis=maecenas&congue=rhoncus", "user_link": "http://google.de/augue.jsp?maecenas=non&ut=velit&massa=donec&quis=diam&augue=neque&luctus=vestibulum&tincidunt=eget&nulla=vulputate&mollis=ut&molestie=ultrices&lorem=vel&quisque=augue&ut=vestibulum&erat=ante&curabitur=ipsum&gravida=primis&nisi=in&at=faucibus&nibh=orci&in=luctus&hac=et&habitasse=ultrices&platea=posuere&dictumst=cubilia&aliquam=curae&augue=donec&quam=pharetra&sollicitudin=magna&vitae=vestibulum&consectetuer=aliquet&eget=ultrices&rutrum=erat&at=tortor&lorem=sollicitudin&integer=mi&tincidunt=sit&ante=amet&vel=lobortis&ipsum=sapien&praesent=sapien&blandit=non&lacinia=mi&erat=integer&vestibulum=ac&sed=neque&magna=duis&at=bibendum&nunc=morbi&commodo=non&placerat=quam&praesent=nec&blandit=dui&nam=luctus&nulla=rutrum&integer=nulla&pede=tellus&justo=in&lacinia=sagittis&eget=dui&tincidunt=vel&eget=nisl&tempus=duis&vel=ac&pede=nibh&morbi=fusce&porttitor=lacus&lorem=purus&id=aliquet&ligula=at&suspendisse=feugiat&ornare=non&consequat=pretium&lectus=quis&in=lectus&est=suspendisse&risus=potenti&auctor=in&sed=eleifend&tristique=quam&in=a&tempus=odio&sit=in&amet=hac&sem=habitasse&fusce=platea&consequat=dictumst&nulla=maecenas&nisl=ut&nunc=massa&nisl=quis&duis=augue&bibendum=luctus&felis=tincidunt&sed=nulla&interdum=mollis&venenatis=molestie&turpis=lorem&enim=quisque" },
  2: { "id": 2, "creator_id": 2, "title": "S21: The Khmer Rouge Death Machine (S-21, la machine de mort Khmère rouge)", "description": "lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra", "created_at": "3/25/2021", "closes_at": "1/2/2021", "admin_link": "https://surveymonkey.com/elementum/ligula.json?vestibulum=odio&ante=porttitor&ipsum=id&primis=consequat&in=in&faucibus=consequat&orci=ut&luctus=nulla&et=sed&ultrices=accumsan&posuere=felis&cubilia=ut&curae=at&donec=dolor&pharetra=quis&magna=odio&vestibulum=consequat&aliquet=varius&ultrices=integer&erat=ac&tortor=leo&sollicitudin=pellentesque&mi=ultrices&sit=mattis&amet=odio&lobortis=donec&sapien=vitae&sapien=nisi&non=nam&mi=ultrices&integer=libero&ac=non&neque=mattis", "user_link": "http://guardian.co.uk/quam.json?odio=vivamus&cras=vel&mi=nulla&pede=eget&malesuada=eros&in=elementum&imperdiet=pellentesque&et=quisque&commodo=porta&vulputate=volutpat&justo=erat&in=quisque&blandit=erat&ultrices=eros&enim=viverra&lorem=eget&ipsum=congue&dolor=eget&sit=semper&amet=rutrum&consectetuer=nulla&adipiscing=nunc&elit=purus&proin=phasellus&interdum=in&mauris=felis&non=donec&ligula=semper&pellentesque=sapien&ultrices=a&phasellus=libero&id=nam&sapien=dui&in=proin&sapien=leo&iaculis=odio&congue=porttitor&vivamus=id&metus=consequat&arcu=in&adipiscing=consequat&molestie=ut&hendrerit=nulla&at=sed&vulputate=accumsan&vitae=felis&nisl=ut&aenean=at&lectus=dolor&pellentesque=quis&eget=odio&nunc=consequat&donec=varius&quis=integer&orci=ac&eget=leo&orci=pellentesque&vehicula=ultrices&condimentum=mattis&curabitur=odio&in=donec&libero=vitae&ut=nisi&massa=nam&volutpat=ultrices&convallis=libero" },
  3: { "id": 3, "creator_id": 3, "title": "Kid Stays in the Picture, The", "description": null, "created_at": "6/9/2021", "closes_at": "9/18/2020", "admin_link": "http://woothemes.com/orci/pede/venenatis.png?ipsum=erat&aliquam=id&non=mauris&mauris=vulputate&morbi=elementum&non=nullam&lectus=varius&aliquam=nulla&sit=facilisi&amet=cras&diam=non&in=velit&magna=nec&bibendum=nisi&imperdiet=vulputate&nullam=nonummy&orci=maecenas&pede=tincidunt&venenatis=lacus&non=at&sodales=velit&sed=vivamus&tincidunt=vel&eu=nulla&felis=eget&fusce=eros&posuere=elementum&felis=pellentesque&sed=quisque&lacus=porta&morbi=volutpat&sem=erat&mauris=quisque&laoreet=erat&ut=eros&rhoncus=viverra&aliquet=eget&pulvinar=congue&sed=eget&nisl=semper&nunc=rutrum&rhoncus=nulla&dui=nunc&vel=purus&sem=phasellus&sed=in", "user_link": "http://nifty.com/nulla.aspx?malesuada=vel&in=augue&imperdiet=vestibulum&et=rutrum&commodo=rutrum&vulputate=neque&justo=aenean&in=auctor&blandit=gravida&ultrices=sem&enim=praesent&lorem=id&ipsum=massa&dolor=id&sit=nisl&amet=venenatis&consectetuer=lacinia&adipiscing=aenean&elit=sit&proin=amet&interdum=justo&mauris=morbi&non=ut&ligula=odio&pellentesque=cras&ultrices=mi&phasellus=pede&id=malesuada&sapien=in&in=imperdiet&sapien=et&iaculis=commodo&congue=vulputate&vivamus=justo&metus=in&arcu=blandit&adipiscing=ultrices&molestie=enim&hendrerit=lorem&at=ipsum&vulputate=dolor&vitae=sit&nisl=amet&aenean=consectetuer&lectus=adipiscing&pellentesque=elit&eget=proin&nunc=interdum&donec=mauris&quis=non&orci=ligula&eget=pellentesque&orci=ultrices&vehicula=phasellus&condimentum=id&curabitur=sapien&in=in&libero=sapien&ut=iaculis&massa=congue&volutpat=vivamus&convallis=metus&morbi=arcu&odio=adipiscing&odio=molestie&elementum=hendrerit&eu=at&interdum=vulputate&eu=vitae&tincidunt=nisl&in=aenean&leo=lectus&maecenas=pellentesque&pulvinar=eget&lobortis=nunc&est=donec&phasellus=quis&sit=orci&amet=eget&erat=orci&nulla=vehicula" },
  4: { "id": 4, "creator_id": 4, "title": "Walk Softly, Stranger", "description": "fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus", "created_at": "10/23/2020", "closes_at": "11/23/2020", "admin_link": "http://wunderground.com/porttitor.jsp?nulla=consectetuer&eget=adipiscing&eros=elit&elementum=proin&pellentesque=risus&quisque=praesent&porta=lectus&volutpat=vestibulum&erat=quam&quisque=sapien&erat=varius&eros=ut&viverra=blandit&eget=non&congue=interdum&eget=in&semper=ante", "user_link": "http://indiatimes.com/consequat/morbi/a/ipsum.html?morbi=nec&non=sem&lectus=duis&aliquam=aliquam&sit=convallis&amet=nunc&diam=proin&in=at&magna=turpis&bibendum=a&imperdiet=pede&nullam=posuere&orci=nonummy&pede=integer&venenatis=non&non=velit&sodales=donec&sed=diam&tincidunt=neque&eu=vestibulum&felis=eget&fusce=vulputate&posuere=ut&felis=ultrices&sed=vel&lacus=augue&morbi=vestibulum&sem=ante&mauris=ipsum&laoreet=primis&ut=in&rhoncus=faucibus&aliquet=orci&pulvinar=luctus&sed=et&nisl=ultrices&nunc=posuere&rhoncus=cubilia&dui=curae&vel=donec&sem=pharetra&sed=magna&sagittis=vestibulum&nam=aliquet&congue=ultrices&risus=erat&semper=tortor&porta=sollicitudin&volutpat=mi&quam=sit&pede=amet&lobortis=lobortis&ligula=sapien&sit=sapien&amet=non&eleifend=mi&pede=integer&libero=ac&quis=neque&orci=duis&nullam=bibendum&molestie=morbi&nibh=non&in=quam&lectus=nec&pellentesque=dui&at=luctus&nulla=rutrum&suspendisse=nulla&potenti=tellus&cras=in&in=sagittis&purus=dui&eu=vel&magna=nisl&vulputate=duis&luctus=ac&cum=nibh" },
  5: { "id": 5, "creator_id": 5, "title": "Law and Order", "description": "consequat ut nulla sed accumsan felis ut at dolor quis odio consequat", "created_at": "3/25/2021", "closes_at": "3/14/2021", "admin_link": "http://cbc.ca/tincidunt/eget/tempus/vel/pede.html?nec=massa&nisi=tempor&volutpat=convallis&eleifend=nulla&donec=neque&ut=libero&dolor=convallis&morbi=eget&vel=eleifend&lectus=luctus&in=ultricies&quam=eu&fringilla=nibh&rhoncus=quisque&mauris=id&enim=justo&leo=sit&rhoncus=amet&sed=sapien&vestibulum=dignissim&sit=vestibulum&amet=vestibulum&cursus=ante&id=ipsum&turpis=primis&integer=in&aliquet=faucibus&massa=orci&id=luctus&lobortis=et", "user_link": "http://icq.com/nec.xml?felis=viverra&sed=eget&interdum=congue&venenatis=eget&turpis=semper&enim=rutrum&blandit=nulla&mi=nunc&in=purus&porttitor=phasellus&pede=in&justo=felis&eu=donec&massa=semper&donec=sapien&dapibus=a&duis=libero&at=nam&velit=dui&eu=proin&est=leo&congue=odio&elementum=porttitor&in=id&hac=consequat&habitasse=in&platea=consequat&dictumst=ut&morbi=nulla&vestibulum=sed&velit=accumsan&id=felis&pretium=ut&iaculis=at&diam=dolor&erat=quis&fermentum=odio&justo=consequat&nec=varius&condimentum=integer&neque=ac&sapien=leo&placerat=pellentesque&ante=ultrices&nulla=mattis&justo=odio&aliquam=donec&quis=vitae&turpis=nisi&eget=nam&elit=ultrices&sodales=libero&scelerisque=non&mauris=mattis&sit=pulvinar&amet=nulla&eros=pede&suspendisse=ullamcorper&accumsan=augue&tortor=a&quis=suscipit&turpis=nulla&sed=elit&ante=ac" }
}

const poll_options = {
  1: { "id": 1, "poll_id": 1, "title": "Cost Accountant", "description": "dapibus duis at velit eu est", "points": 0 },
  2: { "id": 2, "poll_id": 1, "title": "Project Manager", "description": null, "points": 0 },
  3: { "id": 3, "poll_id": 1, "title": "Analyst Programmer", "description": "ultrices", "points": 0 },
  4: { "id": 4, "poll_id": 1, "title": "Design Engineer", "description": "vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet", "points": 0 },
  5: { "id": 5, "poll_id": 1, "title": "Health Coach II", "description": null, "points": 0 },
  6: { "id": 6, "poll_id": 1, "title": "Health Coach III", "description": null, "points": 0 }
}

const user_answers = {
  1: { "id": 1, "poll_id": 1, "poll_option_id": 1, "name": "Bone" },
  2: { "id": 2, "poll_id": 1, "poll_option_id": 2, "name": "Errol" },
  3: { "id": 3, "poll_id": 1, "poll_option_id": 3, "name": "Chaunce" },
  4: { "id": 4, "poll_id": 1, "poll_option_id": 4, "name": "Kirstyn" },
  5: { "id": 5, "poll_id": 1, "poll_option_id": 5, "name": "Hyacinthe" }
}

module.exports = { users, polls, poll_options, user_answers };
